//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="providerStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="providerCircuitId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="providerOrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provisioningNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provisioningNodeRouter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qosProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="techType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productSku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rsn" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ipAddress" type="{http://www.megapath.com/m360}IpAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ipDetails" type="{http://www.megapath.com/m360}IpDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="vpi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vci" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vrf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="circuitLogin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="circuitPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessDetails", propOrder = {
    "productName",
    "provider",
    "providerStatusCode",
    "providerCircuitId",
    "providerOrderId",
    "provisioningNode",
    "provisioningNodeRouter",
    "qosProfile",
    "techType",
    "productSku",
    "rsn",
    "ipAddress",
    "ipDetails",
    "vpi",
    "vci",
    "vrf",
    "circuitLogin",
    "circuitPassword"
})
public class AccessDetails {

    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String provider;
    @XmlElement(required = true)
    protected String providerStatusCode;
    @XmlElement(required = true)
    protected String providerCircuitId;
    @XmlElement(required = true)
    protected String providerOrderId;
    @XmlElement(required = true)
    protected String provisioningNode;
    @XmlElement(required = true)
    protected String provisioningNodeRouter;
    @XmlElement(required = true)
    protected String qosProfile;
    @XmlElement(required = true)
    protected String techType;
    @XmlElement(required = true)
    protected String productSku;
    protected long rsn;
    protected List<IpAddress> ipAddress;
    protected List<IpDetails> ipDetails;
    @XmlElement(required = true)
    protected String vpi;
    @XmlElement(required = true)
    protected String vci;
    @XmlElement(required = true)
    protected String vrf;
    @XmlElement(required = true)
    protected String circuitLogin;
    @XmlElement(required = true)
    protected String circuitPassword;

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the provider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Sets the value of the provider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvider(String value) {
        this.provider = value;
    }

    /**
     * Gets the value of the providerStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderStatusCode() {
        return providerStatusCode;
    }

    /**
     * Sets the value of the providerStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderStatusCode(String value) {
        this.providerStatusCode = value;
    }

    /**
     * Gets the value of the providerCircuitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderCircuitId() {
        return providerCircuitId;
    }

    /**
     * Sets the value of the providerCircuitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderCircuitId(String value) {
        this.providerCircuitId = value;
    }

    /**
     * Gets the value of the providerOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderOrderId() {
        return providerOrderId;
    }

    /**
     * Sets the value of the providerOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderOrderId(String value) {
        this.providerOrderId = value;
    }

    /**
     * Gets the value of the provisioningNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisioningNode() {
        return provisioningNode;
    }

    /**
     * Sets the value of the provisioningNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisioningNode(String value) {
        this.provisioningNode = value;
    }

    /**
     * Gets the value of the provisioningNodeRouter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisioningNodeRouter() {
        return provisioningNodeRouter;
    }

    /**
     * Sets the value of the provisioningNodeRouter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisioningNodeRouter(String value) {
        this.provisioningNodeRouter = value;
    }

    /**
     * Gets the value of the qosProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQosProfile() {
        return qosProfile;
    }

    /**
     * Sets the value of the qosProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQosProfile(String value) {
        this.qosProfile = value;
    }

    /**
     * Gets the value of the techType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechType() {
        return techType;
    }

    /**
     * Sets the value of the techType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechType(String value) {
        this.techType = value;
    }

    /**
     * Gets the value of the productSku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSku() {
        return productSku;
    }

    /**
     * Sets the value of the productSku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSku(String value) {
        this.productSku = value;
    }

    /**
     * Gets the value of the rsn property.
     * 
     */
    public long getRsn() {
        return rsn;
    }

    /**
     * Sets the value of the rsn property.
     * 
     */
    public void setRsn(long value) {
        this.rsn = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpAddress }
     * 
     * 
     */
    public List<IpAddress> getIpAddress() {
        if (ipAddress == null) {
            ipAddress = new ArrayList<IpAddress>();
        }
        return this.ipAddress;
    }

    /**
     * Gets the value of the ipDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpDetails }
     * 
     * 
     */
    public List<IpDetails> getIpDetails() {
        if (ipDetails == null) {
            ipDetails = new ArrayList<IpDetails>();
        }
        return this.ipDetails;
    }

    /**
     * Gets the value of the vpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpi() {
        return vpi;
    }

    /**
     * Sets the value of the vpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpi(String value) {
        this.vpi = value;
    }

    /**
     * Gets the value of the vci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVci() {
        return vci;
    }

    /**
     * Sets the value of the vci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVci(String value) {
        this.vci = value;
    }

    /**
     * Gets the value of the vrf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrf() {
        return vrf;
    }

    /**
     * Sets the value of the vrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrf(String value) {
        this.vrf = value;
    }

    /**
     * Gets the value of the circuitLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuitLogin() {
        return circuitLogin;
    }

    /**
     * Sets the value of the circuitLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuitLogin(String value) {
        this.circuitLogin = value;
    }

    /**
     * Gets the value of the circuitPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuitPassword() {
        return circuitPassword;
    }

    /**
     * Sets the value of the circuitPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuitPassword(String value) {
        this.circuitPassword = value;
    }

}
