//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccountSearchResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountSearchResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accountNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="accountHierarchy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="previousAccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="organizationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hasAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasVoip" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasMss" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasHostedIt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="accountSegment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountSearchResult", propOrder = {
    "accountNumber",
    "accountHierarchy",
    "previousAccountNumber",
    "companyName",
    "organizationName",
    "contactName",
    "serviceAddress",
    "hasAccess",
    "hasVoip",
    "hasMss",
    "hasHostedIt",
    "accountSegment",
    "serviceStatus"
})
public class AccountSearchResult {

    protected long accountNumber;
    @XmlElement(required = true)
    protected String accountHierarchy;
    @XmlElement(required = true)
    protected String previousAccountNumber;
    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String organizationName;
    @XmlElement(required = true)
    protected String contactName;
    @XmlElement(required = true)
    protected String serviceAddress;
    protected boolean hasAccess;
    protected boolean hasVoip;
    protected boolean hasMss;
    protected boolean hasHostedIt;
    @XmlElement(required = true)
    protected String accountSegment;
    @XmlElement(required = true)
    protected String serviceStatus;

    /**
     * Gets the value of the accountNumber property.
     * 
     */
    public long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     */
    public void setAccountNumber(long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the accountHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountHierarchy() {
        return accountHierarchy;
    }

    /**
     * Sets the value of the accountHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountHierarchy(String value) {
        this.accountHierarchy = value;
    }

    /**
     * Gets the value of the previousAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousAccountNumber() {
        return previousAccountNumber;
    }

    /**
     * Sets the value of the previousAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousAccountNumber(String value) {
        this.previousAccountNumber = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganizationName(String value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the serviceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Sets the value of the serviceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAddress(String value) {
        this.serviceAddress = value;
    }

    /**
     * Gets the value of the hasAccess property.
     * 
     */
    public boolean isHasAccess() {
        return hasAccess;
    }

    /**
     * Sets the value of the hasAccess property.
     * 
     */
    public void setHasAccess(boolean value) {
        this.hasAccess = value;
    }

    /**
     * Gets the value of the hasVoip property.
     * 
     */
    public boolean isHasVoip() {
        return hasVoip;
    }

    /**
     * Sets the value of the hasVoip property.
     * 
     */
    public void setHasVoip(boolean value) {
        this.hasVoip = value;
    }

    /**
     * Gets the value of the hasMss property.
     * 
     */
    public boolean isHasMss() {
        return hasMss;
    }

    /**
     * Sets the value of the hasMss property.
     * 
     */
    public void setHasMss(boolean value) {
        this.hasMss = value;
    }

    /**
     * Gets the value of the hasHostedIt property.
     * 
     */
    public boolean isHasHostedIt() {
        return hasHostedIt;
    }

    /**
     * Sets the value of the hasHostedIt property.
     * 
     */
    public void setHasHostedIt(boolean value) {
        this.hasHostedIt = value;
    }

    /**
     * Gets the value of the accountSegment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountSegment() {
        return accountSegment;
    }

    /**
     * Sets the value of the accountSegment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountSegment(String value) {
        this.accountSegment = value;
    }

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceStatus(String value) {
        this.serviceStatus = value;
    }

}
