//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AffiliateSearchForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AffiliateSearchForm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="affiliateName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apVendorId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="affiliateId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AffiliateSearchForm", propOrder = {
    "affiliateName",
    "apVendorId",
    "affiliateId",
    "customerId"
})
public class AffiliateSearchForm {

    @XmlElement(required = true)
    protected String affiliateName;
    protected long apVendorId;
    protected long affiliateId;
    protected long customerId;

    /**
     * Gets the value of the affiliateName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliateName() {
        return affiliateName;
    }

    /**
     * Sets the value of the affiliateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliateName(String value) {
        this.affiliateName = value;
    }

    /**
     * Gets the value of the apVendorId property.
     * 
     */
    public long getApVendorId() {
        return apVendorId;
    }

    /**
     * Sets the value of the apVendorId property.
     * 
     */
    public void setApVendorId(long value) {
        this.apVendorId = value;
    }

    /**
     * Gets the value of the affiliateId property.
     * 
     */
    public long getAffiliateId() {
        return affiliateId;
    }

    /**
     * Sets the value of the affiliateId property.
     * 
     */
    public void setAffiliateId(long value) {
        this.affiliateId = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     */
    public long getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     */
    public void setCustomerId(long value) {
        this.customerId = value;
    }

}
