//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillingOverview complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillingOverview">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lastInvoiceAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastInvoiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentSinceLastInvoice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currentDueOutstanding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pastDueAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dueAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accountPastDue" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="legacySystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billToAccountNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingOverview", propOrder = {
    "lastInvoiceAmount",
    "lastInvoiceDate",
    "paymentSinceLastInvoice",
    "lastPaymentDate",
    "currentDueOutstanding",
    "dueDate",
    "pastDueAmount",
    "dueAmount",
    "accountPastDue",
    "legacySystem",
    "billToAccountNumber"
})
public class BillingOverview {

    @XmlElement(required = true)
    protected String lastInvoiceAmount;
    @XmlElement(required = true)
    protected String lastInvoiceDate;
    @XmlElement(required = true)
    protected String paymentSinceLastInvoice;
    @XmlElement(required = true)
    protected String lastPaymentDate;
    @XmlElement(required = true)
    protected String currentDueOutstanding;
    @XmlElement(required = true)
    protected String dueDate;
    @XmlElement(required = true)
    protected String pastDueAmount;
    @XmlElement(required = true)
    protected String dueAmount;
    protected boolean accountPastDue;
    @XmlElement(required = true)
    protected String legacySystem;
    protected long billToAccountNumber;

    /**
     * Gets the value of the lastInvoiceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastInvoiceAmount() {
        return lastInvoiceAmount;
    }

    /**
     * Sets the value of the lastInvoiceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastInvoiceAmount(String value) {
        this.lastInvoiceAmount = value;
    }

    /**
     * Gets the value of the lastInvoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastInvoiceDate() {
        return lastInvoiceDate;
    }

    /**
     * Sets the value of the lastInvoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastInvoiceDate(String value) {
        this.lastInvoiceDate = value;
    }

    /**
     * Gets the value of the paymentSinceLastInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentSinceLastInvoice() {
        return paymentSinceLastInvoice;
    }

    /**
     * Sets the value of the paymentSinceLastInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentSinceLastInvoice(String value) {
        this.paymentSinceLastInvoice = value;
    }

    /**
     * Gets the value of the lastPaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastPaymentDate() {
        return lastPaymentDate;
    }

    /**
     * Sets the value of the lastPaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastPaymentDate(String value) {
        this.lastPaymentDate = value;
    }

    /**
     * Gets the value of the currentDueOutstanding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentDueOutstanding() {
        return currentDueOutstanding;
    }

    /**
     * Sets the value of the currentDueOutstanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentDueOutstanding(String value) {
        this.currentDueOutstanding = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the pastDueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPastDueAmount() {
        return pastDueAmount;
    }

    /**
     * Sets the value of the pastDueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPastDueAmount(String value) {
        this.pastDueAmount = value;
    }

    /**
     * Gets the value of the dueAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueAmount() {
        return dueAmount;
    }

    /**
     * Sets the value of the dueAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueAmount(String value) {
        this.dueAmount = value;
    }

    /**
     * Gets the value of the accountPastDue property.
     * 
     */
    public boolean isAccountPastDue() {
        return accountPastDue;
    }

    /**
     * Sets the value of the accountPastDue property.
     * 
     */
    public void setAccountPastDue(boolean value) {
        this.accountPastDue = value;
    }

    /**
     * Gets the value of the legacySystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegacySystem() {
        return legacySystem;
    }

    /**
     * Sets the value of the legacySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegacySystem(String value) {
        this.legacySystem = value;
    }

    /**
     * Gets the value of the billToAccountNumber property.
     * 
     */
    public long getBillToAccountNumber() {
        return billToAccountNumber;
    }

    /**
     * Sets the value of the billToAccountNumber property.
     * 
     */
    public void setBillToAccountNumber(long value) {
        this.billToAccountNumber = value;
    }

}
