//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvcDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvcDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="evcId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerServiceTypeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="evcBandwidth" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="cosValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cosName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nidLanPort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cloudServiceProvider" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cloudServiceProviderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vlanIdNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ceVlanPreserve" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ceVlanValidate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="ceVlanValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enableDynamicRouting" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="numOfIp" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="vpn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="vpnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selectedVpn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="routingProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanUserRouterIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanSubnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="poolSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dhcpPoolIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeWan" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wanUserRouterIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanSubnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="evcValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="partnerServiceId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="staticIpBlocks" type="{http://www.megapath.com/m360}StaticIpBlocks" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvcDetails", propOrder = {
    "evcId",
    "partnerServiceTypeId",
    "evcBandwidth",
    "cosValue",
    "cosName",
    "nidLanPort",
    "cloudServiceProvider",
    "cloudServiceProviderName",
    "vlanIdNumber",
    "ceVlanPreserve",
    "ceVlanValidate",
    "ceVlanValue",
    "enableDynamicRouting",
    "numOfIp",
    "vpn",
    "vpnName",
    "selectedVpn",
    "routingProtocol",
    "lanUserRouterIp",
    "lanSubnetMask",
    "dhcp",
    "poolSize",
    "dhcpPoolIpAddress",
    "cpeWan",
    "wanUserRouterIp",
    "wanSubnetMask",
    "evcValue",
    "partnerServiceId",
    "staticIpBlocks"
})
public class EvcDetails {

    protected int evcId;
    protected int partnerServiceTypeId;
    protected float evcBandwidth;
    protected int cosValue;
    @XmlElement(required = true)
    protected String cosName;
    @XmlElement(required = true)
    protected String nidLanPort;
    protected int cloudServiceProvider;
    @XmlElement(required = true)
    protected String cloudServiceProviderName;
    protected int vlanIdNumber;
    protected boolean ceVlanPreserve;
    protected boolean ceVlanValidate;
    @XmlElement(required = true)
    protected String ceVlanValue;
    protected boolean enableDynamicRouting;
    protected int numOfIp;
    protected int vpn;
    @XmlElement(required = true)
    protected String vpnName;
    @XmlElement(required = true)
    protected String selectedVpn;
    @XmlElement(required = true)
    protected String routingProtocol;
    @XmlElement(required = true)
    protected String lanUserRouterIp;
    @XmlElement(required = true)
    protected String lanSubnetMask;
    protected boolean dhcp;
    protected int poolSize;
    @XmlElement(required = true)
    protected String dhcpPoolIpAddress;
    protected boolean cpeWan;
    @XmlElement(required = true)
    protected String wanUserRouterIp;
    @XmlElement(required = true)
    protected String wanSubnetMask;
    protected int evcValue;
    protected int partnerServiceId;
    protected List<StaticIpBlocks> staticIpBlocks;

    /**
     * Gets the value of the evcId property.
     * 
     */
    public int getEvcId() {
        return evcId;
    }

    /**
     * Sets the value of the evcId property.
     * 
     */
    public void setEvcId(int value) {
        this.evcId = value;
    }

    /**
     * Gets the value of the partnerServiceTypeId property.
     * 
     */
    public int getPartnerServiceTypeId() {
        return partnerServiceTypeId;
    }

    /**
     * Sets the value of the partnerServiceTypeId property.
     * 
     */
    public void setPartnerServiceTypeId(int value) {
        this.partnerServiceTypeId = value;
    }

    /**
     * Gets the value of the evcBandwidth property.
     * 
     */
    public float getEvcBandwidth() {
        return evcBandwidth;
    }

    /**
     * Sets the value of the evcBandwidth property.
     * 
     */
    public void setEvcBandwidth(float value) {
        this.evcBandwidth = value;
    }

    /**
     * Gets the value of the cosValue property.
     * 
     */
    public int getCosValue() {
        return cosValue;
    }

    /**
     * Sets the value of the cosValue property.
     * 
     */
    public void setCosValue(int value) {
        this.cosValue = value;
    }

    /**
     * Gets the value of the cosName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCosName() {
        return cosName;
    }

    /**
     * Sets the value of the cosName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCosName(String value) {
        this.cosName = value;
    }

    /**
     * Gets the value of the nidLanPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNidLanPort() {
        return nidLanPort;
    }

    /**
     * Sets the value of the nidLanPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNidLanPort(String value) {
        this.nidLanPort = value;
    }

    /**
     * Gets the value of the cloudServiceProvider property.
     * 
     */
    public int getCloudServiceProvider() {
        return cloudServiceProvider;
    }

    /**
     * Sets the value of the cloudServiceProvider property.
     * 
     */
    public void setCloudServiceProvider(int value) {
        this.cloudServiceProvider = value;
    }

    /**
     * Gets the value of the cloudServiceProviderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudServiceProviderName() {
        return cloudServiceProviderName;
    }

    /**
     * Sets the value of the cloudServiceProviderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudServiceProviderName(String value) {
        this.cloudServiceProviderName = value;
    }

    /**
     * Gets the value of the vlanIdNumber property.
     * 
     */
    public int getVlanIdNumber() {
        return vlanIdNumber;
    }

    /**
     * Sets the value of the vlanIdNumber property.
     * 
     */
    public void setVlanIdNumber(int value) {
        this.vlanIdNumber = value;
    }

    /**
     * Gets the value of the ceVlanPreserve property.
     * 
     */
    public boolean isCeVlanPreserve() {
        return ceVlanPreserve;
    }

    /**
     * Sets the value of the ceVlanPreserve property.
     * 
     */
    public void setCeVlanPreserve(boolean value) {
        this.ceVlanPreserve = value;
    }

    /**
     * Gets the value of the ceVlanValidate property.
     * 
     */
    public boolean isCeVlanValidate() {
        return ceVlanValidate;
    }

    /**
     * Sets the value of the ceVlanValidate property.
     * 
     */
    public void setCeVlanValidate(boolean value) {
        this.ceVlanValidate = value;
    }

    /**
     * Gets the value of the ceVlanValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCeVlanValue() {
        return ceVlanValue;
    }

    /**
     * Sets the value of the ceVlanValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCeVlanValue(String value) {
        this.ceVlanValue = value;
    }

    /**
     * Gets the value of the enableDynamicRouting property.
     * 
     */
    public boolean isEnableDynamicRouting() {
        return enableDynamicRouting;
    }

    /**
     * Sets the value of the enableDynamicRouting property.
     * 
     */
    public void setEnableDynamicRouting(boolean value) {
        this.enableDynamicRouting = value;
    }

    /**
     * Gets the value of the numOfIp property.
     * 
     */
    public int getNumOfIp() {
        return numOfIp;
    }

    /**
     * Sets the value of the numOfIp property.
     * 
     */
    public void setNumOfIp(int value) {
        this.numOfIp = value;
    }

    /**
     * Gets the value of the vpn property.
     * 
     */
    public int getVpn() {
        return vpn;
    }

    /**
     * Sets the value of the vpn property.
     * 
     */
    public void setVpn(int value) {
        this.vpn = value;
    }

    /**
     * Gets the value of the vpnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpnName() {
        return vpnName;
    }

    /**
     * Sets the value of the vpnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpnName(String value) {
        this.vpnName = value;
    }

    /**
     * Gets the value of the selectedVpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedVpn() {
        return selectedVpn;
    }

    /**
     * Sets the value of the selectedVpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedVpn(String value) {
        this.selectedVpn = value;
    }

    /**
     * Gets the value of the routingProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingProtocol() {
        return routingProtocol;
    }

    /**
     * Sets the value of the routingProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingProtocol(String value) {
        this.routingProtocol = value;
    }

    /**
     * Gets the value of the lanUserRouterIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanUserRouterIp() {
        return lanUserRouterIp;
    }

    /**
     * Sets the value of the lanUserRouterIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanUserRouterIp(String value) {
        this.lanUserRouterIp = value;
    }

    /**
     * Gets the value of the lanSubnetMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanSubnetMask() {
        return lanSubnetMask;
    }

    /**
     * Sets the value of the lanSubnetMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanSubnetMask(String value) {
        this.lanSubnetMask = value;
    }

    /**
     * Gets the value of the dhcp property.
     * 
     */
    public boolean isDhcp() {
        return dhcp;
    }

    /**
     * Sets the value of the dhcp property.
     * 
     */
    public void setDhcp(boolean value) {
        this.dhcp = value;
    }

    /**
     * Gets the value of the poolSize property.
     * 
     */
    public int getPoolSize() {
        return poolSize;
    }

    /**
     * Sets the value of the poolSize property.
     * 
     */
    public void setPoolSize(int value) {
        this.poolSize = value;
    }

    /**
     * Gets the value of the dhcpPoolIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpPoolIpAddress() {
        return dhcpPoolIpAddress;
    }

    /**
     * Sets the value of the dhcpPoolIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpPoolIpAddress(String value) {
        this.dhcpPoolIpAddress = value;
    }

    /**
     * Gets the value of the cpeWan property.
     * 
     */
    public boolean isCpeWan() {
        return cpeWan;
    }

    /**
     * Sets the value of the cpeWan property.
     * 
     */
    public void setCpeWan(boolean value) {
        this.cpeWan = value;
    }

    /**
     * Gets the value of the wanUserRouterIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanUserRouterIp() {
        return wanUserRouterIp;
    }

    /**
     * Sets the value of the wanUserRouterIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanUserRouterIp(String value) {
        this.wanUserRouterIp = value;
    }

    /**
     * Gets the value of the wanSubnetMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanSubnetMask() {
        return wanSubnetMask;
    }

    /**
     * Sets the value of the wanSubnetMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanSubnetMask(String value) {
        this.wanSubnetMask = value;
    }

    /**
     * Gets the value of the evcValue property.
     * 
     */
    public int getEvcValue() {
        return evcValue;
    }

    /**
     * Sets the value of the evcValue property.
     * 
     */
    public void setEvcValue(int value) {
        this.evcValue = value;
    }

    /**
     * Gets the value of the partnerServiceId property.
     * 
     */
    public int getPartnerServiceId() {
        return partnerServiceId;
    }

    /**
     * Sets the value of the partnerServiceId property.
     * 
     */
    public void setPartnerServiceId(int value) {
        this.partnerServiceId = value;
    }

    /**
     * Gets the value of the staticIpBlocks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the staticIpBlocks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaticIpBlocks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StaticIpBlocks }
     * 
     * 
     */
    public List<StaticIpBlocks> getStaticIpBlocks() {
        if (staticIpBlocks == null) {
            staticIpBlocks = new ArrayList<StaticIpBlocks>();
        }
        return this.staticIpBlocks;
    }

}
