//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Invoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Invoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="invoiceNumber" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="invoiceDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="previousBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currentCharges" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalDue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adjustment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lateFee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="payment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pdfUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Invoice", propOrder = {
    "invoiceNumber",
    "invoiceDate",
    "dueDate",
    "previousBalance",
    "currentCharges",
    "totalDue",
    "adjustment",
    "lateFee",
    "payment",
    "pdfUrl"
})
public class Invoice {

    protected long invoiceNumber;
    @XmlElement(required = true)
    protected String invoiceDate;
    @XmlElement(required = true)
    protected String dueDate;
    @XmlElement(required = true)
    protected String previousBalance;
    @XmlElement(required = true)
    protected String currentCharges;
    @XmlElement(required = true)
    protected String totalDue;
    @XmlElement(required = true)
    protected String adjustment;
    @XmlElement(required = true)
    protected String lateFee;
    @XmlElement(required = true)
    protected String payment;
    @XmlElement(required = true)
    protected String pdfUrl;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     */
    public long getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     */
    public void setInvoiceNumber(long value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceDate(String value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the previousBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousBalance() {
        return previousBalance;
    }

    /**
     * Sets the value of the previousBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousBalance(String value) {
        this.previousBalance = value;
    }

    /**
     * Gets the value of the currentCharges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentCharges() {
        return currentCharges;
    }

    /**
     * Sets the value of the currentCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentCharges(String value) {
        this.currentCharges = value;
    }

    /**
     * Gets the value of the totalDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalDue() {
        return totalDue;
    }

    /**
     * Sets the value of the totalDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalDue(String value) {
        this.totalDue = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustment() {
        return adjustment;
    }

    /**
     * Sets the value of the adjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustment(String value) {
        this.adjustment = value;
    }

    /**
     * Gets the value of the lateFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLateFee() {
        return lateFee;
    }

    /**
     * Sets the value of the lateFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLateFee(String value) {
        this.lateFee = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayment(String value) {
        this.payment = value;
    }

    /**
     * Gets the value of the pdfUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfUrl() {
        return pdfUrl;
    }

    /**
     * Sets the value of the pdfUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfUrl(String value) {
        this.pdfUrl = value;
    }

}
