//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IpDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IpDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cidr" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subnetAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstUsableIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastUsableIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipPoolName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipPoolType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IpDetails", propOrder = {
    "ipAddress",
    "cidr",
    "subnetMask",
    "subnetAddress",
    "firstUsableIpAddress",
    "lastUsableIpAddress",
    "ipPoolName",
    "ipPoolType",
    "ipType"
})
public class IpDetails {

    @XmlElement(required = true)
    protected String ipAddress;
    protected int cidr;
    @XmlElement(required = true)
    protected String subnetMask;
    @XmlElement(required = true)
    protected String subnetAddress;
    @XmlElement(required = true)
    protected String firstUsableIpAddress;
    @XmlElement(required = true)
    protected String lastUsableIpAddress;
    @XmlElement(required = true)
    protected String ipPoolName;
    @XmlElement(required = true)
    protected String ipPoolType;
    @XmlElement(required = true)
    protected String ipType;

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the cidr property.
     * 
     */
    public int getCidr() {
        return cidr;
    }

    /**
     * Sets the value of the cidr property.
     * 
     */
    public void setCidr(int value) {
        this.cidr = value;
    }

    /**
     * Gets the value of the subnetMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetMask() {
        return subnetMask;
    }

    /**
     * Sets the value of the subnetMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetMask(String value) {
        this.subnetMask = value;
    }

    /**
     * Gets the value of the subnetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubnetAddress() {
        return subnetAddress;
    }

    /**
     * Sets the value of the subnetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubnetAddress(String value) {
        this.subnetAddress = value;
    }

    /**
     * Gets the value of the firstUsableIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstUsableIpAddress() {
        return firstUsableIpAddress;
    }

    /**
     * Sets the value of the firstUsableIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstUsableIpAddress(String value) {
        this.firstUsableIpAddress = value;
    }

    /**
     * Gets the value of the lastUsableIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUsableIpAddress() {
        return lastUsableIpAddress;
    }

    /**
     * Sets the value of the lastUsableIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUsableIpAddress(String value) {
        this.lastUsableIpAddress = value;
    }

    /**
     * Gets the value of the ipPoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpPoolName() {
        return ipPoolName;
    }

    /**
     * Sets the value of the ipPoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpPoolName(String value) {
        this.ipPoolName = value;
    }

    /**
     * Gets the value of the ipPoolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpPoolType() {
        return ipPoolType;
    }

    /**
     * Sets the value of the ipPoolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpPoolType(String value) {
        this.ipPoolType = value;
    }

    /**
     * Gets the value of the ipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpType() {
        return ipType;
    }

    /**
     * Sets the value of the ipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpType(String value) {
        this.ipType = value;
    }

}
