//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Line complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Line">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lsn" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="serviceAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bondingInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateConnected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateDisconnected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessDetails" type="{http://www.megapath.com/m360}AccessDetails"/>
 *         &lt;element name="service" type="{http://www.megapath.com/m360}Service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="otherService" type="{http://www.megapath.com/m360}Service" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="equipment" type="{http://www.megapath.com/m360}Equipment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="voipTelephoneNumber" type="{http://www.megapath.com/m360}VoipTelephoneNumber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dispatch" type="{http://www.megapath.com/m360}Dispatch" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="associatedLSN" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="associatedType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Line", propOrder = {
    "lsn",
    "serviceAddress",
    "lineType",
    "lineStatus",
    "billcode",
    "bondingInfo",
    "dateConnected",
    "dateDisconnected",
    "accessDetails",
    "service",
    "otherService",
    "equipment",
    "voipTelephoneNumber",
    "dispatch",
    "associatedLSN",
    "associatedType"
})
public class Line {

    protected long lsn;
    @XmlElement(required = true)
    protected String serviceAddress;
    @XmlElement(required = true)
    protected String lineType;
    @XmlElement(required = true)
    protected String lineStatus;
    @XmlElement(required = true)
    protected String billcode;
    @XmlElement(required = true)
    protected String bondingInfo;
    @XmlElement(required = true)
    protected String dateConnected;
    @XmlElement(required = true)
    protected String dateDisconnected;
    @XmlElement(required = true)
    protected AccessDetails accessDetails;
    protected List<Service> service;
    protected List<Service> otherService;
    protected List<Equipment> equipment;
    protected List<VoipTelephoneNumber> voipTelephoneNumber;
    protected List<Dispatch> dispatch;
    protected long associatedLSN;
    @XmlElement(required = true)
    protected String associatedType;

    /**
     * Gets the value of the lsn property.
     * 
     */
    public long getLsn() {
        return lsn;
    }

    /**
     * Sets the value of the lsn property.
     * 
     */
    public void setLsn(long value) {
        this.lsn = value;
    }

    /**
     * Gets the value of the serviceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Sets the value of the serviceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAddress(String value) {
        this.serviceAddress = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the lineStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineStatus() {
        return lineStatus;
    }

    /**
     * Sets the value of the lineStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineStatus(String value) {
        this.lineStatus = value;
    }

    /**
     * Gets the value of the billcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillcode() {
        return billcode;
    }

    /**
     * Sets the value of the billcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillcode(String value) {
        this.billcode = value;
    }

    /**
     * Gets the value of the bondingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondingInfo() {
        return bondingInfo;
    }

    /**
     * Sets the value of the bondingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondingInfo(String value) {
        this.bondingInfo = value;
    }

    /**
     * Gets the value of the dateConnected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateConnected() {
        return dateConnected;
    }

    /**
     * Sets the value of the dateConnected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateConnected(String value) {
        this.dateConnected = value;
    }

    /**
     * Gets the value of the dateDisconnected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateDisconnected() {
        return dateDisconnected;
    }

    /**
     * Sets the value of the dateDisconnected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDisconnected(String value) {
        this.dateDisconnected = value;
    }

    /**
     * Gets the value of the accessDetails property.
     * 
     * @return
     *     possible object is
     *     {@link AccessDetails }
     *     
     */
    public AccessDetails getAccessDetails() {
        return accessDetails;
    }

    /**
     * Sets the value of the accessDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessDetails }
     *     
     */
    public void setAccessDetails(AccessDetails value) {
        this.accessDetails = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the service property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the otherService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getOtherService() {
        if (otherService == null) {
            otherService = new ArrayList<Service>();
        }
        return this.otherService;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the equipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEquipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Equipment }
     * 
     * 
     */
    public List<Equipment> getEquipment() {
        if (equipment == null) {
            equipment = new ArrayList<Equipment>();
        }
        return this.equipment;
    }

    /**
     * Gets the value of the voipTelephoneNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voipTelephoneNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoipTelephoneNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VoipTelephoneNumber }
     * 
     * 
     */
    public List<VoipTelephoneNumber> getVoipTelephoneNumber() {
        if (voipTelephoneNumber == null) {
            voipTelephoneNumber = new ArrayList<VoipTelephoneNumber>();
        }
        return this.voipTelephoneNumber;
    }

    /**
     * Gets the value of the dispatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dispatch }
     * 
     * 
     */
    public List<Dispatch> getDispatch() {
        if (dispatch == null) {
            dispatch = new ArrayList<Dispatch>();
        }
        return this.dispatch;
    }

    /**
     * Gets the value of the associatedLSN property.
     * 
     */
    public long getAssociatedLSN() {
        return associatedLSN;
    }

    /**
     * Sets the value of the associatedLSN property.
     * 
     */
    public void setAssociatedLSN(long value) {
        this.associatedLSN = value;
    }

    /**
     * Gets the value of the associatedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedType() {
        return associatedType;
    }

    /**
     * Sets the value of the associatedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedType(String value) {
        this.associatedType = value;
    }

}
