//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NidLanPortDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NidLanPortDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cpeModelId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeModelPortId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpePortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="interfaceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NidLanPortDetails", propOrder = {
    "cpeModelId",
    "cpeModelPortId",
    "cpePortName",
    "interfaceType"
})
public class NidLanPortDetails {

    @XmlElement(required = true)
    protected String cpeModelId;
    @XmlElement(required = true)
    protected String cpeModelPortId;
    @XmlElement(required = true)
    protected String cpePortName;
    @XmlElement(required = true)
    protected String interfaceType;

    /**
     * Gets the value of the cpeModelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeModelId() {
        return cpeModelId;
    }

    /**
     * Sets the value of the cpeModelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeModelId(String value) {
        this.cpeModelId = value;
    }

    /**
     * Gets the value of the cpeModelPortId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeModelPortId() {
        return cpeModelPortId;
    }

    /**
     * Sets the value of the cpeModelPortId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeModelPortId(String value) {
        this.cpeModelPortId = value;
    }

    /**
     * Gets the value of the cpePortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpePortName() {
        return cpePortName;
    }

    /**
     * Sets the value of the cpePortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpePortName(String value) {
        this.cpePortName = value;
    }

    /**
     * Gets the value of the interfaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * Sets the value of the interfaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceType(String value) {
        this.interfaceType = value;
    }

}
