//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.matrix360.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.matrix360.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link M360Response }
     * 
     */
    public M360Response createM360Response() {
        return new M360Response();
    }

    /**
     * Create an instance of {@link AccountDetails }
     * 
     */
    public AccountDetails createAccountDetails() {
        return new AccountDetails();
    }

    /**
     * Create an instance of {@link NotificationDetailsResponse }
     * 
     */
    public NotificationDetailsResponse createNotificationDetailsResponse() {
        return new NotificationDetailsResponse();
    }

    /**
     * Create an instance of {@link AuthenticationApiResponse }
     * 
     */
    public AuthenticationApiResponse createAuthenticationApiResponse() {
        return new AuthenticationApiResponse();
    }

    /**
     * Create an instance of {@link UserVerificationApiResponse }
     * 
     */
    public UserVerificationApiResponse createUserVerificationApiResponse() {
        return new UserVerificationApiResponse();
    }

    /**
     * Create an instance of {@link ServiceDetails }
     * 
     */
    public ServiceDetails createServiceDetails() {
        return new ServiceDetails();
    }

    /**
     * Create an instance of {@link ServiceSummary }
     * 
     */
    public ServiceSummary createServiceSummary() {
        return new ServiceSummary();
    }

    /**
     * Create an instance of {@link AccountSearchResult }
     * 
     */
    public AccountSearchResult createAccountSearchResult() {
        return new AccountSearchResult();
    }

    /**
     * Create an instance of {@link OrderDetails }
     * 
     */
    public OrderDetails createOrderDetails() {
        return new OrderDetails();
    }

    /**
     * Create an instance of {@link ProductBundle }
     * 
     */
    public ProductBundle createProductBundle() {
        return new ProductBundle();
    }

    /**
     * Create an instance of {@link ChildAccount }
     * 
     */
    public ChildAccount createChildAccount() {
        return new ChildAccount();
    }

    /**
     * Create an instance of {@link BillingDetails }
     * 
     */
    public BillingDetails createBillingDetails() {
        return new BillingDetails();
    }

    /**
     * Create an instance of {@link ContractDetails }
     * 
     */
    public ContractDetails createContractDetails() {
        return new ContractDetails();
    }

    /**
     * Create an instance of {@link OnNetCircuit }
     * 
     */
    public OnNetCircuit createOnNetCircuit() {
        return new OnNetCircuit();
    }

    /**
     * Create an instance of {@link Ticket }
     * 
     */
    public Ticket createTicket() {
        return new Ticket();
    }

    /**
     * Create an instance of {@link OnNetVpnDetails }
     * 
     */
    public OnNetVpnDetails createOnNetVpnDetails() {
        return new OnNetVpnDetails();
    }

    /**
     * Create an instance of {@link EvplCspDetails }
     * 
     */
    public EvplCspDetails createEvplCspDetails() {
        return new EvplCspDetails();
    }

    /**
     * Create an instance of {@link NidLanPortDetails }
     * 
     */
    public NidLanPortDetails createNidLanPortDetails() {
        return new NidLanPortDetails();
    }

    /**
     * Create an instance of {@link EvcDetails }
     * 
     */
    public EvcDetails createEvcDetails() {
        return new EvcDetails();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link CustomerSearchForm }
     * 
     */
    public CustomerSearchForm createCustomerSearchForm() {
        return new CustomerSearchForm();
    }

    /**
     * Create an instance of {@link OnNetLoop }
     * 
     */
    public OnNetLoop createOnNetLoop() {
        return new OnNetLoop();
    }

    /**
     * Create an instance of {@link TicketAttachment }
     * 
     */
    public TicketAttachment createTicketAttachment() {
        return new TicketAttachment();
    }

    /**
     * Create an instance of {@link OnNetDispatch }
     * 
     */
    public OnNetDispatch createOnNetDispatch() {
        return new OnNetDispatch();
    }

    /**
     * Create an instance of {@link MosesTicket }
     * 
     */
    public MosesTicket createMosesTicket() {
        return new MosesTicket();
    }

    /**
     * Create an instance of {@link DownloadServiceSummaryItem }
     * 
     */
    public DownloadServiceSummaryItem createDownloadServiceSummaryItem() {
        return new DownloadServiceSummaryItem();
    }

    /**
     * Create an instance of {@link OnNetIPService }
     * 
     */
    public OnNetIPService createOnNetIPService() {
        return new OnNetIPService();
    }

    /**
     * Create an instance of {@link AccessDetails }
     * 
     */
    public AccessDetails createAccessDetails() {
        return new AccessDetails();
    }

    /**
     * Create an instance of {@link OrderNote }
     * 
     */
    public OrderNote createOrderNote() {
        return new OrderNote();
    }

    /**
     * Create an instance of {@link OnNetOrder }
     * 
     */
    public OnNetOrder createOnNetOrder() {
        return new OnNetOrder();
    }

    /**
     * Create an instance of {@link VoipTelephoneNumber }
     * 
     */
    public VoipTelephoneNumber createVoipTelephoneNumber() {
        return new VoipTelephoneNumber();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link Equipment }
     * 
     */
    public Equipment createEquipment() {
        return new Equipment();
    }

    /**
     * Create an instance of {@link CustomerOverview }
     * 
     */
    public CustomerOverview createCustomerOverview() {
        return new CustomerOverview();
    }

    /**
     * Create an instance of {@link StaticIpBlocks }
     * 
     */
    public StaticIpBlocks createStaticIpBlocks() {
        return new StaticIpBlocks();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link VoipService }
     * 
     */
    public VoipService createVoipService() {
        return new VoipService();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link NotificationDetails }
     * 
     */
    public NotificationDetails createNotificationDetails() {
        return new NotificationDetails();
    }

    /**
     * Create an instance of {@link ProductPricing }
     * 
     */
    public ProductPricing createProductPricing() {
        return new ProductPricing();
    }

    /**
     * Create an instance of {@link ProductBundleMember }
     * 
     */
    public ProductBundleMember createProductBundleMember() {
        return new ProductBundleMember();
    }

    /**
     * Create an instance of {@link VoipServiceHeader }
     * 
     */
    public VoipServiceHeader createVoipServiceHeader() {
        return new VoipServiceHeader();
    }

    /**
     * Create an instance of {@link OrderLineItem }
     * 
     */
    public OrderLineItem createOrderLineItem() {
        return new OrderLineItem();
    }

    /**
     * Create an instance of {@link OutageDetails }
     * 
     */
    public OutageDetails createOutageDetails() {
        return new OutageDetails();
    }

    /**
     * Create an instance of {@link AffiliateSearchForm }
     * 
     */
    public AffiliateSearchForm createAffiliateSearchForm() {
        return new AffiliateSearchForm();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link BillingOverview }
     * 
     */
    public BillingOverview createBillingOverview() {
        return new BillingOverview();
    }

    /**
     * Create an instance of {@link CustomerContact }
     * 
     */
    public CustomerContact createCustomerContact() {
        return new CustomerContact();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link OrderMilestone }
     * 
     */
    public OrderMilestone createOrderMilestone() {
        return new OrderMilestone();
    }

    /**
     * Create an instance of {@link OnNetTicket }
     * 
     */
    public OnNetTicket createOnNetTicket() {
        return new OnNetTicket();
    }

    /**
     * Create an instance of {@link Dispatch }
     * 
     */
    public Dispatch createDispatch() {
        return new Dispatch();
    }

    /**
     * Create an instance of {@link IpAddress }
     * 
     */
    public IpAddress createIpAddress() {
        return new IpAddress();
    }

    /**
     * Create an instance of {@link OnNetCpeService }
     * 
     */
    public OnNetCpeService createOnNetCpeService() {
        return new OnNetCpeService();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link VoipDetails }
     * 
     */
    public VoipDetails createVoipDetails() {
        return new VoipDetails();
    }

    /**
     * Create an instance of {@link OnNetAccessService }
     * 
     */
    public OnNetAccessService createOnNetAccessService() {
        return new OnNetAccessService();
    }

    /**
     * Create an instance of {@link IpDetails }
     * 
     */
    public IpDetails createIpDetails() {
        return new IpDetails();
    }

    /**
     * Create an instance of {@link OnNetService }
     * 
     */
    public OnNetService createOnNetService() {
        return new OnNetService();
    }

    /**
     * Create an instance of {@link ServiceProperty }
     * 
     */
    public ServiceProperty createServiceProperty() {
        return new ServiceProperty();
    }

    /**
     * Create an instance of {@link Outage }
     * 
     */
    public Outage createOutage() {
        return new Outage();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

}
