//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnNetLoop complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnNetLoop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loopId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carrierCircuitId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fictitiousPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clliCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lineSplit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="techType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pqDistanceFromCO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voiceClecAcnaCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loopServiceMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zclliCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loopOrderedOn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceProvisionedOn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ilec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnNetLoop", propOrder = {
    "loopId",
    "carrierCircuitId",
    "fictitiousPhoneNumber",
    "clliCode",
    "lineSplit",
    "techType",
    "status",
    "pqDistanceFromCO",
    "voiceClecAcnaCode",
    "dateAccepted",
    "loopServiceMethod",
    "zclliCode",
    "loopOrderedOn",
    "serviceProvisionedOn",
    "ilec"
})
public class OnNetLoop {

    @XmlElement(required = true)
    protected String loopId;
    @XmlElement(required = true)
    protected String carrierCircuitId;
    @XmlElement(required = true)
    protected String fictitiousPhoneNumber;
    @XmlElement(required = true)
    protected String clliCode;
    @XmlElement(required = true)
    protected String lineSplit;
    @XmlElement(required = true)
    protected String techType;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String pqDistanceFromCO;
    @XmlElement(required = true)
    protected String voiceClecAcnaCode;
    @XmlElement(required = true)
    protected String dateAccepted;
    @XmlElement(required = true)
    protected String loopServiceMethod;
    @XmlElement(required = true)
    protected String zclliCode;
    @XmlElement(required = true)
    protected String loopOrderedOn;
    @XmlElement(required = true)
    protected String serviceProvisionedOn;
    @XmlElement(required = true)
    protected String ilec;

    /**
     * Gets the value of the loopId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopId() {
        return loopId;
    }

    /**
     * Sets the value of the loopId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopId(String value) {
        this.loopId = value;
    }

    /**
     * Gets the value of the carrierCircuitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierCircuitId() {
        return carrierCircuitId;
    }

    /**
     * Sets the value of the carrierCircuitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierCircuitId(String value) {
        this.carrierCircuitId = value;
    }

    /**
     * Gets the value of the fictitiousPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFictitiousPhoneNumber() {
        return fictitiousPhoneNumber;
    }

    /**
     * Sets the value of the fictitiousPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFictitiousPhoneNumber(String value) {
        this.fictitiousPhoneNumber = value;
    }

    /**
     * Gets the value of the clliCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClliCode() {
        return clliCode;
    }

    /**
     * Sets the value of the clliCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClliCode(String value) {
        this.clliCode = value;
    }

    /**
     * Gets the value of the lineSplit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSplit() {
        return lineSplit;
    }

    /**
     * Sets the value of the lineSplit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSplit(String value) {
        this.lineSplit = value;
    }

    /**
     * Gets the value of the techType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechType() {
        return techType;
    }

    /**
     * Sets the value of the techType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechType(String value) {
        this.techType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the pqDistanceFromCO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPqDistanceFromCO() {
        return pqDistanceFromCO;
    }

    /**
     * Sets the value of the pqDistanceFromCO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPqDistanceFromCO(String value) {
        this.pqDistanceFromCO = value;
    }

    /**
     * Gets the value of the voiceClecAcnaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoiceClecAcnaCode() {
        return voiceClecAcnaCode;
    }

    /**
     * Sets the value of the voiceClecAcnaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoiceClecAcnaCode(String value) {
        this.voiceClecAcnaCode = value;
    }

    /**
     * Gets the value of the dateAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAccepted() {
        return dateAccepted;
    }

    /**
     * Sets the value of the dateAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAccepted(String value) {
        this.dateAccepted = value;
    }

    /**
     * Gets the value of the loopServiceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopServiceMethod() {
        return loopServiceMethod;
    }

    /**
     * Sets the value of the loopServiceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopServiceMethod(String value) {
        this.loopServiceMethod = value;
    }

    /**
     * Gets the value of the zclliCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZclliCode() {
        return zclliCode;
    }

    /**
     * Sets the value of the zclliCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZclliCode(String value) {
        this.zclliCode = value;
    }

    /**
     * Gets the value of the loopOrderedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoopOrderedOn() {
        return loopOrderedOn;
    }

    /**
     * Sets the value of the loopOrderedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoopOrderedOn(String value) {
        this.loopOrderedOn = value;
    }

    /**
     * Gets the value of the serviceProvisionedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceProvisionedOn() {
        return serviceProvisionedOn;
    }

    /**
     * Sets the value of the serviceProvisionedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceProvisionedOn(String value) {
        this.serviceProvisionedOn = value;
    }

    /**
     * Gets the value of the ilec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIlec() {
        return ilec;
    }

    /**
     * Sets the value of the ilec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIlec(String value) {
        this.ilec = value;
    }

}
