//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnNetCircuit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnNetCircuit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="circuitNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="order" type="{http://www.megapath.com/m360}OnNetOrder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ticket" type="{http://www.megapath.com/m360}OnNetTicket" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="service" type="{http://www.megapath.com/m360}OnNetService" minOccurs="0"/>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wholesalePartner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="enterpriseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dispatch" type="{http://www.megapath.com/m360}OnNetDispatch" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateConnected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateDisconnected" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="loop" type="{http://www.megapath.com/m360}OnNetLoop" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bondingInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parentCircuitNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vpnDetails" type="{http://www.megapath.com/m360}OnNetVpnDetails"/>
 *         &lt;element name="evcDetails" type="{http://www.megapath.com/m360}EvcDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="siteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnNetCircuit", propOrder = {
    "circuitNumber",
    "order",
    "ticket",
    "service",
    "companyName",
    "wholesalePartner",
    "enterpriseName",
    "siteAddress",
    "dispatch",
    "status",
    "dateConnected",
    "dateDisconnected",
    "loop",
    "bondingInfo",
    "parentCircuitNumber",
    "vpnDetails",
    "evcDetails",
    "siteName"
})
public class OnNetCircuit {

    @XmlElement(required = true)
    protected String circuitNumber;
    protected List<OnNetOrder> order;
    protected List<OnNetTicket> ticket;
    protected OnNetService service;
    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String wholesalePartner;
    @XmlElement(required = true)
    protected String enterpriseName;
    @XmlElement(required = true)
    protected String siteAddress;
    protected List<OnNetDispatch> dispatch;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String dateConnected;
    @XmlElement(required = true)
    protected String dateDisconnected;
    protected List<OnNetLoop> loop;
    @XmlElement(required = true)
    protected String bondingInfo;
    @XmlElement(required = true)
    protected String parentCircuitNumber;
    @XmlElement(required = true)
    protected OnNetVpnDetails vpnDetails;
    protected List<EvcDetails> evcDetails;
    @XmlElement(required = true)
    protected String siteName;

    /**
     * Gets the value of the circuitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircuitNumber() {
        return circuitNumber;
    }

    /**
     * Sets the value of the circuitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircuitNumber(String value) {
        this.circuitNumber = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the order property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnNetOrder }
     * 
     * 
     */
    public List<OnNetOrder> getOrder() {
        if (order == null) {
            order = new ArrayList<OnNetOrder>();
        }
        return this.order;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ticket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTicket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnNetTicket }
     * 
     * 
     */
    public List<OnNetTicket> getTicket() {
        if (ticket == null) {
            ticket = new ArrayList<OnNetTicket>();
        }
        return this.ticket;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetService }
     *     
     */
    public OnNetService getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetService }
     *     
     */
    public void setService(OnNetService value) {
        this.service = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the wholesalePartner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWholesalePartner() {
        return wholesalePartner;
    }

    /**
     * Sets the value of the wholesalePartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWholesalePartner(String value) {
        this.wholesalePartner = value;
    }

    /**
     * Gets the value of the enterpriseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * Sets the value of the enterpriseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseName(String value) {
        this.enterpriseName = value;
    }

    /**
     * Gets the value of the siteAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteAddress() {
        return siteAddress;
    }

    /**
     * Sets the value of the siteAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteAddress(String value) {
        this.siteAddress = value;
    }

    /**
     * Gets the value of the dispatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnNetDispatch }
     * 
     * 
     */
    public List<OnNetDispatch> getDispatch() {
        if (dispatch == null) {
            dispatch = new ArrayList<OnNetDispatch>();
        }
        return this.dispatch;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dateConnected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateConnected() {
        return dateConnected;
    }

    /**
     * Sets the value of the dateConnected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateConnected(String value) {
        this.dateConnected = value;
    }

    /**
     * Gets the value of the dateDisconnected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateDisconnected() {
        return dateDisconnected;
    }

    /**
     * Sets the value of the dateDisconnected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDisconnected(String value) {
        this.dateDisconnected = value;
    }

    /**
     * Gets the value of the loop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnNetLoop }
     * 
     * 
     */
    public List<OnNetLoop> getLoop() {
        if (loop == null) {
            loop = new ArrayList<OnNetLoop>();
        }
        return this.loop;
    }

    /**
     * Gets the value of the bondingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondingInfo() {
        return bondingInfo;
    }

    /**
     * Sets the value of the bondingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondingInfo(String value) {
        this.bondingInfo = value;
    }

    /**
     * Gets the value of the parentCircuitNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentCircuitNumber() {
        return parentCircuitNumber;
    }

    /**
     * Sets the value of the parentCircuitNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentCircuitNumber(String value) {
        this.parentCircuitNumber = value;
    }

    /**
     * Gets the value of the vpnDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetVpnDetails }
     *     
     */
    public OnNetVpnDetails getVpnDetails() {
        return vpnDetails;
    }

    /**
     * Sets the value of the vpnDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetVpnDetails }
     *     
     */
    public void setVpnDetails(OnNetVpnDetails value) {
        this.vpnDetails = value;
    }

    /**
     * Gets the value of the evcDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evcDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvcDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvcDetails }
     * 
     * 
     */
    public List<EvcDetails> getEvcDetails() {
        if (evcDetails == null) {
            evcDetails = new ArrayList<EvcDetails>();
        }
        return this.evcDetails;
    }

    /**
     * Gets the value of the siteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * Sets the value of the siteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteName(String value) {
        this.siteName = value;
    }

}
