//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnNetCpeService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnNetCpeService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cpeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpePassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeProvider" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeConfigurer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeManagedByCovad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeVendorSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeEncapsulation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpeNetworking" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpEnabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpServerIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpPoolStartIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpPoolIpCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanRouterIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lansubnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="interworkingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanRoutingProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanTestIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanSecTestIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanRouterIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wansubnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanRoutingProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partnerRouterIp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pppUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pppPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pppDomainName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipAddress" type="{http://www.megapath.com/m360}IpAddress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="primaryCpe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnNetCpeService", propOrder = {
    "cpeName",
    "cpePassword",
    "cpeProvider",
    "cpeConfigurer",
    "cpeManagedByCovad",
    "cpeVendorSerialNumber",
    "cpeEncapsulation",
    "cpeNetworking",
    "dhcpEnabled",
    "dhcpServerIp",
    "dhcpPoolStartIp",
    "dhcpPoolIpCount",
    "lanRouterIp",
    "lansubnetMask",
    "interworkingType",
    "lanRoutingProtocol",
    "lanTestIp",
    "lanSecTestIp",
    "wanRouterIp",
    "wansubnetMask",
    "networkNumber",
    "wanRoutingProtocol",
    "partnerRouterIp",
    "pppUserName",
    "pppPassword",
    "pppDomainName",
    "ipAddress",
    "primaryCpe"
})
public class OnNetCpeService {

    @XmlElement(required = true)
    protected String cpeName;
    @XmlElement(required = true)
    protected String cpePassword;
    @XmlElement(required = true)
    protected String cpeProvider;
    @XmlElement(required = true)
    protected String cpeConfigurer;
    @XmlElement(required = true)
    protected String cpeManagedByCovad;
    @XmlElement(required = true)
    protected String cpeVendorSerialNumber;
    @XmlElement(required = true)
    protected String cpeEncapsulation;
    @XmlElement(required = true)
    protected String cpeNetworking;
    @XmlElement(required = true)
    protected String dhcpEnabled;
    @XmlElement(required = true)
    protected String dhcpServerIp;
    @XmlElement(required = true)
    protected String dhcpPoolStartIp;
    @XmlElement(required = true)
    protected String dhcpPoolIpCount;
    @XmlElement(required = true)
    protected String lanRouterIp;
    @XmlElement(required = true)
    protected String lansubnetMask;
    @XmlElement(required = true)
    protected String interworkingType;
    @XmlElement(required = true)
    protected String lanRoutingProtocol;
    @XmlElement(required = true)
    protected String lanTestIp;
    @XmlElement(required = true)
    protected String lanSecTestIp;
    @XmlElement(required = true)
    protected String wanRouterIp;
    @XmlElement(required = true)
    protected String wansubnetMask;
    @XmlElement(required = true)
    protected String networkNumber;
    @XmlElement(required = true)
    protected String wanRoutingProtocol;
    @XmlElement(required = true)
    protected String partnerRouterIp;
    @XmlElement(required = true)
    protected String pppUserName;
    @XmlElement(required = true)
    protected String pppPassword;
    @XmlElement(required = true)
    protected String pppDomainName;
    protected List<IpAddress> ipAddress;
    @XmlElement(required = true)
    protected String primaryCpe;

    /**
     * Gets the value of the cpeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeName() {
        return cpeName;
    }

    /**
     * Sets the value of the cpeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeName(String value) {
        this.cpeName = value;
    }

    /**
     * Gets the value of the cpePassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpePassword() {
        return cpePassword;
    }

    /**
     * Sets the value of the cpePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpePassword(String value) {
        this.cpePassword = value;
    }

    /**
     * Gets the value of the cpeProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeProvider() {
        return cpeProvider;
    }

    /**
     * Sets the value of the cpeProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeProvider(String value) {
        this.cpeProvider = value;
    }

    /**
     * Gets the value of the cpeConfigurer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeConfigurer() {
        return cpeConfigurer;
    }

    /**
     * Sets the value of the cpeConfigurer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeConfigurer(String value) {
        this.cpeConfigurer = value;
    }

    /**
     * Gets the value of the cpeManagedByCovad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeManagedByCovad() {
        return cpeManagedByCovad;
    }

    /**
     * Sets the value of the cpeManagedByCovad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeManagedByCovad(String value) {
        this.cpeManagedByCovad = value;
    }

    /**
     * Gets the value of the cpeVendorSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeVendorSerialNumber() {
        return cpeVendorSerialNumber;
    }

    /**
     * Sets the value of the cpeVendorSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeVendorSerialNumber(String value) {
        this.cpeVendorSerialNumber = value;
    }

    /**
     * Gets the value of the cpeEncapsulation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeEncapsulation() {
        return cpeEncapsulation;
    }

    /**
     * Sets the value of the cpeEncapsulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeEncapsulation(String value) {
        this.cpeEncapsulation = value;
    }

    /**
     * Gets the value of the cpeNetworking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpeNetworking() {
        return cpeNetworking;
    }

    /**
     * Sets the value of the cpeNetworking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpeNetworking(String value) {
        this.cpeNetworking = value;
    }

    /**
     * Gets the value of the dhcpEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpEnabled() {
        return dhcpEnabled;
    }

    /**
     * Sets the value of the dhcpEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpEnabled(String value) {
        this.dhcpEnabled = value;
    }

    /**
     * Gets the value of the dhcpServerIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpServerIp() {
        return dhcpServerIp;
    }

    /**
     * Sets the value of the dhcpServerIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpServerIp(String value) {
        this.dhcpServerIp = value;
    }

    /**
     * Gets the value of the dhcpPoolStartIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpPoolStartIp() {
        return dhcpPoolStartIp;
    }

    /**
     * Sets the value of the dhcpPoolStartIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpPoolStartIp(String value) {
        this.dhcpPoolStartIp = value;
    }

    /**
     * Gets the value of the dhcpPoolIpCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpPoolIpCount() {
        return dhcpPoolIpCount;
    }

    /**
     * Sets the value of the dhcpPoolIpCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpPoolIpCount(String value) {
        this.dhcpPoolIpCount = value;
    }

    /**
     * Gets the value of the lanRouterIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanRouterIp() {
        return lanRouterIp;
    }

    /**
     * Sets the value of the lanRouterIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanRouterIp(String value) {
        this.lanRouterIp = value;
    }

    /**
     * Gets the value of the lansubnetMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLansubnetMask() {
        return lansubnetMask;
    }

    /**
     * Sets the value of the lansubnetMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLansubnetMask(String value) {
        this.lansubnetMask = value;
    }

    /**
     * Gets the value of the interworkingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterworkingType() {
        return interworkingType;
    }

    /**
     * Sets the value of the interworkingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterworkingType(String value) {
        this.interworkingType = value;
    }

    /**
     * Gets the value of the lanRoutingProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanRoutingProtocol() {
        return lanRoutingProtocol;
    }

    /**
     * Sets the value of the lanRoutingProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanRoutingProtocol(String value) {
        this.lanRoutingProtocol = value;
    }

    /**
     * Gets the value of the lanTestIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanTestIp() {
        return lanTestIp;
    }

    /**
     * Sets the value of the lanTestIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanTestIp(String value) {
        this.lanTestIp = value;
    }

    /**
     * Gets the value of the lanSecTestIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanSecTestIp() {
        return lanSecTestIp;
    }

    /**
     * Sets the value of the lanSecTestIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanSecTestIp(String value) {
        this.lanSecTestIp = value;
    }

    /**
     * Gets the value of the wanRouterIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanRouterIp() {
        return wanRouterIp;
    }

    /**
     * Sets the value of the wanRouterIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanRouterIp(String value) {
        this.wanRouterIp = value;
    }

    /**
     * Gets the value of the wansubnetMask property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWansubnetMask() {
        return wansubnetMask;
    }

    /**
     * Sets the value of the wansubnetMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWansubnetMask(String value) {
        this.wansubnetMask = value;
    }

    /**
     * Gets the value of the networkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkNumber() {
        return networkNumber;
    }

    /**
     * Sets the value of the networkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkNumber(String value) {
        this.networkNumber = value;
    }

    /**
     * Gets the value of the wanRoutingProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanRoutingProtocol() {
        return wanRoutingProtocol;
    }

    /**
     * Sets the value of the wanRoutingProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanRoutingProtocol(String value) {
        this.wanRoutingProtocol = value;
    }

    /**
     * Gets the value of the partnerRouterIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRouterIp() {
        return partnerRouterIp;
    }

    /**
     * Sets the value of the partnerRouterIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRouterIp(String value) {
        this.partnerRouterIp = value;
    }

    /**
     * Gets the value of the pppUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPppUserName() {
        return pppUserName;
    }

    /**
     * Sets the value of the pppUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPppUserName(String value) {
        this.pppUserName = value;
    }

    /**
     * Gets the value of the pppPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPppPassword() {
        return pppPassword;
    }

    /**
     * Sets the value of the pppPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPppPassword(String value) {
        this.pppPassword = value;
    }

    /**
     * Gets the value of the pppDomainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPppDomainName() {
        return pppDomainName;
    }

    /**
     * Sets the value of the pppDomainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPppDomainName(String value) {
        this.pppDomainName = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpAddress }
     * 
     * 
     */
    public List<IpAddress> getIpAddress() {
        if (ipAddress == null) {
            ipAddress = new ArrayList<IpAddress>();
        }
        return this.ipAddress;
    }

    /**
     * Gets the value of the primaryCpe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryCpe() {
        return primaryCpe;
    }

    /**
     * Sets the value of the primaryCpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryCpe(String value) {
        this.primaryCpe = value;
    }

}
