//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnNetVpnDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnNetVpnDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lanRoutingProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanRoutingProtocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lanSubnet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanSubnet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vpnGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="vpnGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpPoolSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dhcpStartingIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnNetVpnDetails", propOrder = {
    "lanRoutingProtocol",
    "wanRoutingProtocol",
    "lanIP",
    "lanSubnet",
    "wanIP",
    "wanSubnet",
    "vpnGroupId",
    "vpnGroupName",
    "dhcpPoolSize",
    "dhcpStartingIpAddress"
})
public class OnNetVpnDetails {

    @XmlElement(required = true)
    protected String lanRoutingProtocol;
    @XmlElement(required = true)
    protected String wanRoutingProtocol;
    @XmlElement(required = true)
    protected String lanIP;
    @XmlElement(required = true)
    protected String lanSubnet;
    @XmlElement(required = true)
    protected String wanIP;
    @XmlElement(required = true)
    protected String wanSubnet;
    protected int vpnGroupId;
    @XmlElement(required = true)
    protected String vpnGroupName;
    @XmlElement(required = true)
    protected String dhcpPoolSize;
    @XmlElement(required = true)
    protected String dhcpStartingIpAddress;

    /**
     * Gets the value of the lanRoutingProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanRoutingProtocol() {
        return lanRoutingProtocol;
    }

    /**
     * Sets the value of the lanRoutingProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanRoutingProtocol(String value) {
        this.lanRoutingProtocol = value;
    }

    /**
     * Gets the value of the wanRoutingProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanRoutingProtocol() {
        return wanRoutingProtocol;
    }

    /**
     * Sets the value of the wanRoutingProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanRoutingProtocol(String value) {
        this.wanRoutingProtocol = value;
    }

    /**
     * Gets the value of the lanIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanIP() {
        return lanIP;
    }

    /**
     * Sets the value of the lanIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanIP(String value) {
        this.lanIP = value;
    }

    /**
     * Gets the value of the lanSubnet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanSubnet() {
        return lanSubnet;
    }

    /**
     * Sets the value of the lanSubnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanSubnet(String value) {
        this.lanSubnet = value;
    }

    /**
     * Gets the value of the wanIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanIP() {
        return wanIP;
    }

    /**
     * Sets the value of the wanIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanIP(String value) {
        this.wanIP = value;
    }

    /**
     * Gets the value of the wanSubnet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanSubnet() {
        return wanSubnet;
    }

    /**
     * Sets the value of the wanSubnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanSubnet(String value) {
        this.wanSubnet = value;
    }

    /**
     * Gets the value of the vpnGroupId property.
     * 
     */
    public int getVpnGroupId() {
        return vpnGroupId;
    }

    /**
     * Sets the value of the vpnGroupId property.
     * 
     */
    public void setVpnGroupId(int value) {
        this.vpnGroupId = value;
    }

    /**
     * Gets the value of the vpnGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpnGroupName() {
        return vpnGroupName;
    }

    /**
     * Sets the value of the vpnGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpnGroupName(String value) {
        this.vpnGroupName = value;
    }

    /**
     * Gets the value of the dhcpPoolSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpPoolSize() {
        return dhcpPoolSize;
    }

    /**
     * Sets the value of the dhcpPoolSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpPoolSize(String value) {
        this.dhcpPoolSize = value;
    }

    /**
     * Gets the value of the dhcpStartingIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDhcpStartingIpAddress() {
        return dhcpStartingIpAddress;
    }

    /**
     * Sets the value of the dhcpStartingIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDhcpStartingIpAddress(String value) {
        this.dhcpStartingIpAddress = value;
    }

}
