//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OnNetService complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnNetService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessService" type="{http://www.megapath.com/m360}OnNetAccessService"/>
 *         &lt;element name="primaryCpeService" type="{http://www.megapath.com/m360}OnNetCpeService"/>
 *         &lt;element name="secondaryCpeService" type="{http://www.megapath.com/m360}OnNetCpeService"/>
 *         &lt;element name="ipService" type="{http://www.megapath.com/m360}OnNetIPService"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnNetService", propOrder = {
    "accessService",
    "primaryCpeService",
    "secondaryCpeService",
    "ipService"
})
public class OnNetService {

    @XmlElement(required = true)
    protected OnNetAccessService accessService;
    @XmlElement(required = true)
    protected OnNetCpeService primaryCpeService;
    @XmlElement(required = true)
    protected OnNetCpeService secondaryCpeService;
    @XmlElement(required = true)
    protected OnNetIPService ipService;

    /**
     * Gets the value of the accessService property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetAccessService }
     *     
     */
    public OnNetAccessService getAccessService() {
        return accessService;
    }

    /**
     * Sets the value of the accessService property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetAccessService }
     *     
     */
    public void setAccessService(OnNetAccessService value) {
        this.accessService = value;
    }

    /**
     * Gets the value of the primaryCpeService property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetCpeService }
     *     
     */
    public OnNetCpeService getPrimaryCpeService() {
        return primaryCpeService;
    }

    /**
     * Sets the value of the primaryCpeService property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetCpeService }
     *     
     */
    public void setPrimaryCpeService(OnNetCpeService value) {
        this.primaryCpeService = value;
    }

    /**
     * Gets the value of the secondaryCpeService property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetCpeService }
     *     
     */
    public OnNetCpeService getSecondaryCpeService() {
        return secondaryCpeService;
    }

    /**
     * Sets the value of the secondaryCpeService property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetCpeService }
     *     
     */
    public void setSecondaryCpeService(OnNetCpeService value) {
        this.secondaryCpeService = value;
    }

    /**
     * Gets the value of the ipService property.
     * 
     * @return
     *     possible object is
     *     {@link OnNetIPService }
     *     
     */
    public OnNetIPService getIpService() {
        return ipService;
    }

    /**
     * Sets the value of the ipService property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnNetIPService }
     *     
     */
    public void setIpService(OnNetIPService value) {
        this.ipService = value;
    }

}
