//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Outage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Outage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outageEmailId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="outageStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outageEndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="masterTicketNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="masterTicketStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notificationTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notificationType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="notificationContent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Outage", propOrder = {
    "outageEmailId",
    "outageStartTime",
    "outageEndTime",
    "masterTicketNumber",
    "masterTicketStatus",
    "notificationTime",
    "notificationType",
    "notificationContent"
})
public class Outage {

    protected long outageEmailId;
    @XmlElement(required = true)
    protected String outageStartTime;
    @XmlElement(required = true)
    protected String outageEndTime;
    @XmlElement(required = true)
    protected String masterTicketNumber;
    @XmlElement(required = true)
    protected String masterTicketStatus;
    @XmlElement(required = true)
    protected String notificationTime;
    @XmlElement(required = true)
    protected String notificationType;
    @XmlElement(required = true)
    protected String notificationContent;

    /**
     * Gets the value of the outageEmailId property.
     * 
     */
    public long getOutageEmailId() {
        return outageEmailId;
    }

    /**
     * Sets the value of the outageEmailId property.
     * 
     */
    public void setOutageEmailId(long value) {
        this.outageEmailId = value;
    }

    /**
     * Gets the value of the outageStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutageStartTime() {
        return outageStartTime;
    }

    /**
     * Sets the value of the outageStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutageStartTime(String value) {
        this.outageStartTime = value;
    }

    /**
     * Gets the value of the outageEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutageEndTime() {
        return outageEndTime;
    }

    /**
     * Sets the value of the outageEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutageEndTime(String value) {
        this.outageEndTime = value;
    }

    /**
     * Gets the value of the masterTicketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterTicketNumber() {
        return masterTicketNumber;
    }

    /**
     * Sets the value of the masterTicketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterTicketNumber(String value) {
        this.masterTicketNumber = value;
    }

    /**
     * Gets the value of the masterTicketStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterTicketStatus() {
        return masterTicketStatus;
    }

    /**
     * Sets the value of the masterTicketStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterTicketStatus(String value) {
        this.masterTicketStatus = value;
    }

    /**
     * Gets the value of the notificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationTime() {
        return notificationTime;
    }

    /**
     * Sets the value of the notificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationTime(String value) {
        this.notificationTime = value;
    }

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationType(String value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the notificationContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationContent() {
        return notificationContent;
    }

    /**
     * Sets the value of the notificationContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationContent(String value) {
        this.notificationContent = value;
    }

}
