//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutageDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutageDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ongoingOutage" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="outage" type="{http://www.megapath.com/m360}Outage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutageDetails", propOrder = {
    "ongoingOutage",
    "outage"
})
public class OutageDetails {

    protected boolean ongoingOutage;
    protected List<Outage> outage;

    /**
     * Gets the value of the ongoingOutage property.
     * 
     */
    public boolean isOngoingOutage() {
        return ongoingOutage;
    }

    /**
     * Sets the value of the ongoingOutage property.
     * 
     */
    public void setOngoingOutage(boolean value) {
        this.ongoingOutage = value;
    }

    /**
     * Gets the value of the outage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Outage }
     * 
     * 
     */
    public List<Outage> getOutage() {
        if (outage == null) {
            outage = new ArrayList<Outage>();
        }
        return this.outage;
    }

}
