//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 06:08:02 PM IST 
//


package com.matrix360.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VoipDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VoipDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="voipServiceHeader" type="{http://www.megapath.com/m360}VoipServiceHeader" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="voipService" type="{http://www.megapath.com/m360}VoipService" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lsn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mosesCustomerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="voipProductType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="siteName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="e911SubscriberName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broadsoftCustomerUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broadSoftCustomerPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="boradSoftMegaPathUserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="boradSoftMegaPathPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="broadSoftGroupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voipEnterpriseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultPhonePassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupContactName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groupContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mainCpeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mainCpeType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bwVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="wanIpAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="httpUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="httpPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sshUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sshPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mpAdminLogin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mpAdminPassword" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="voicePlatform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VoipDetails", propOrder = {
    "voipServiceHeader",
    "voipService",
    "lsn",
    "mosesCustomerId",
    "voipProductType",
    "siteName",
    "groupId",
    "groupName",
    "e911SubscriberName",
    "broadsoftCustomerUserId",
    "broadSoftCustomerPassword",
    "boradSoftMegaPathUserId",
    "boradSoftMegaPathPassword",
    "broadSoftGroupId",
    "voipEnterpriseId",
    "defaultPhonePassword",
    "timeZone",
    "groupContactName",
    "groupContactPhone",
    "groupContactEmail",
    "mainCpeName",
    "mainCpeType",
    "bwVersion",
    "wanIpAddress",
    "httpUserName",
    "httpPassword",
    "sshUserName",
    "sshPassword",
    "mpAdminLogin",
    "mpAdminPassword",
    "voicePlatform"
})
public class VoipDetails {

    protected List<VoipServiceHeader> voipServiceHeader;
    protected List<VoipService> voipService;
    @XmlElement(required = true)
    protected String lsn;
    protected long mosesCustomerId;
    @XmlElement(required = true)
    protected String voipProductType;
    @XmlElement(required = true)
    protected String siteName;
    @XmlElement(required = true)
    protected String groupId;
    @XmlElement(required = true)
    protected String groupName;
    @XmlElement(required = true)
    protected String e911SubscriberName;
    @XmlElement(required = true)
    protected String broadsoftCustomerUserId;
    @XmlElement(required = true)
    protected String broadSoftCustomerPassword;
    @XmlElement(required = true)
    protected String boradSoftMegaPathUserId;
    @XmlElement(required = true)
    protected String boradSoftMegaPathPassword;
    @XmlElement(required = true)
    protected String broadSoftGroupId;
    @XmlElement(required = true)
    protected String voipEnterpriseId;
    @XmlElement(required = true)
    protected String defaultPhonePassword;
    @XmlElement(required = true)
    protected String timeZone;
    @XmlElement(required = true)
    protected String groupContactName;
    @XmlElement(required = true)
    protected String groupContactPhone;
    @XmlElement(required = true)
    protected String groupContactEmail;
    @XmlElement(required = true)
    protected String mainCpeName;
    @XmlElement(required = true)
    protected String mainCpeType;
    @XmlElement(required = true)
    protected String bwVersion;
    @XmlElement(required = true)
    protected String wanIpAddress;
    @XmlElement(required = true)
    protected String httpUserName;
    @XmlElement(required = true)
    protected String httpPassword;
    @XmlElement(required = true)
    protected String sshUserName;
    @XmlElement(required = true)
    protected String sshPassword;
    @XmlElement(required = true)
    protected String mpAdminLogin;
    @XmlElement(required = true)
    protected String mpAdminPassword;
    @XmlElement(required = true)
    protected String voicePlatform;

    /**
     * Gets the value of the voipServiceHeader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voipServiceHeader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoipServiceHeader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VoipServiceHeader }
     * 
     * 
     */
    public List<VoipServiceHeader> getVoipServiceHeader() {
        if (voipServiceHeader == null) {
            voipServiceHeader = new ArrayList<VoipServiceHeader>();
        }
        return this.voipServiceHeader;
    }

    /**
     * Gets the value of the voipService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voipService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoipService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VoipService }
     * 
     * 
     */
    public List<VoipService> getVoipService() {
        if (voipService == null) {
            voipService = new ArrayList<VoipService>();
        }
        return this.voipService;
    }

    /**
     * Gets the value of the lsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLsn() {
        return lsn;
    }

    /**
     * Sets the value of the lsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLsn(String value) {
        this.lsn = value;
    }

    /**
     * Gets the value of the mosesCustomerId property.
     * 
     */
    public long getMosesCustomerId() {
        return mosesCustomerId;
    }

    /**
     * Sets the value of the mosesCustomerId property.
     * 
     */
    public void setMosesCustomerId(long value) {
        this.mosesCustomerId = value;
    }

    /**
     * Gets the value of the voipProductType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoipProductType() {
        return voipProductType;
    }

    /**
     * Sets the value of the voipProductType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoipProductType(String value) {
        this.voipProductType = value;
    }

    /**
     * Gets the value of the siteName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * Sets the value of the siteName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSiteName(String value) {
        this.siteName = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the e911SubscriberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE911SubscriberName() {
        return e911SubscriberName;
    }

    /**
     * Sets the value of the e911SubscriberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE911SubscriberName(String value) {
        this.e911SubscriberName = value;
    }

    /**
     * Gets the value of the broadsoftCustomerUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroadsoftCustomerUserId() {
        return broadsoftCustomerUserId;
    }

    /**
     * Sets the value of the broadsoftCustomerUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroadsoftCustomerUserId(String value) {
        this.broadsoftCustomerUserId = value;
    }

    /**
     * Gets the value of the broadSoftCustomerPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroadSoftCustomerPassword() {
        return broadSoftCustomerPassword;
    }

    /**
     * Sets the value of the broadSoftCustomerPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroadSoftCustomerPassword(String value) {
        this.broadSoftCustomerPassword = value;
    }

    /**
     * Gets the value of the boradSoftMegaPathUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoradSoftMegaPathUserId() {
        return boradSoftMegaPathUserId;
    }

    /**
     * Sets the value of the boradSoftMegaPathUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoradSoftMegaPathUserId(String value) {
        this.boradSoftMegaPathUserId = value;
    }

    /**
     * Gets the value of the boradSoftMegaPathPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoradSoftMegaPathPassword() {
        return boradSoftMegaPathPassword;
    }

    /**
     * Sets the value of the boradSoftMegaPathPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoradSoftMegaPathPassword(String value) {
        this.boradSoftMegaPathPassword = value;
    }

    /**
     * Gets the value of the broadSoftGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroadSoftGroupId() {
        return broadSoftGroupId;
    }

    /**
     * Sets the value of the broadSoftGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroadSoftGroupId(String value) {
        this.broadSoftGroupId = value;
    }

    /**
     * Gets the value of the voipEnterpriseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoipEnterpriseId() {
        return voipEnterpriseId;
    }

    /**
     * Sets the value of the voipEnterpriseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoipEnterpriseId(String value) {
        this.voipEnterpriseId = value;
    }

    /**
     * Gets the value of the defaultPhonePassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultPhonePassword() {
        return defaultPhonePassword;
    }

    /**
     * Sets the value of the defaultPhonePassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultPhonePassword(String value) {
        this.defaultPhonePassword = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the groupContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupContactName() {
        return groupContactName;
    }

    /**
     * Sets the value of the groupContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupContactName(String value) {
        this.groupContactName = value;
    }

    /**
     * Gets the value of the groupContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupContactPhone() {
        return groupContactPhone;
    }

    /**
     * Sets the value of the groupContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupContactPhone(String value) {
        this.groupContactPhone = value;
    }

    /**
     * Gets the value of the groupContactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupContactEmail() {
        return groupContactEmail;
    }

    /**
     * Sets the value of the groupContactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupContactEmail(String value) {
        this.groupContactEmail = value;
    }

    /**
     * Gets the value of the mainCpeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCpeName() {
        return mainCpeName;
    }

    /**
     * Sets the value of the mainCpeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCpeName(String value) {
        this.mainCpeName = value;
    }

    /**
     * Gets the value of the mainCpeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainCpeType() {
        return mainCpeType;
    }

    /**
     * Sets the value of the mainCpeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainCpeType(String value) {
        this.mainCpeType = value;
    }

    /**
     * Gets the value of the bwVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBwVersion() {
        return bwVersion;
    }

    /**
     * Sets the value of the bwVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBwVersion(String value) {
        this.bwVersion = value;
    }

    /**
     * Gets the value of the wanIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWanIpAddress() {
        return wanIpAddress;
    }

    /**
     * Sets the value of the wanIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWanIpAddress(String value) {
        this.wanIpAddress = value;
    }

    /**
     * Gets the value of the httpUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpUserName() {
        return httpUserName;
    }

    /**
     * Sets the value of the httpUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpUserName(String value) {
        this.httpUserName = value;
    }

    /**
     * Gets the value of the httpPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHttpPassword() {
        return httpPassword;
    }

    /**
     * Sets the value of the httpPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHttpPassword(String value) {
        this.httpPassword = value;
    }

    /**
     * Gets the value of the sshUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSshUserName() {
        return sshUserName;
    }

    /**
     * Sets the value of the sshUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSshUserName(String value) {
        this.sshUserName = value;
    }

    /**
     * Gets the value of the sshPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSshPassword() {
        return sshPassword;
    }

    /**
     * Sets the value of the sshPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSshPassword(String value) {
        this.sshPassword = value;
    }

    /**
     * Gets the value of the mpAdminLogin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpAdminLogin() {
        return mpAdminLogin;
    }

    /**
     * Sets the value of the mpAdminLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpAdminLogin(String value) {
        this.mpAdminLogin = value;
    }

    /**
     * Gets the value of the mpAdminPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMpAdminPassword() {
        return mpAdminPassword;
    }

    /**
     * Sets the value of the mpAdminPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMpAdminPassword(String value) {
        this.mpAdminPassword = value;
    }

    /**
     * Gets the value of the voicePlatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoicePlatform() {
        return voicePlatform;
    }

    /**
     * Sets the value of the voicePlatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoicePlatform(String value) {
        this.voicePlatform = value;
    }

}
